nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: 'API для операций с посадочным материалом.'
            version: 1.0.0
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            security:
                - bearerAuth: [ ]   # применяет Bearer global по умолчанию (можно убрать, если не нужно глобально)
    areas: # to filter documented areas
        default:
            path_patterns: [ '^/api' ]
            host_patterns: [ ]
