nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: 'API для расчёта цены и покупки продуктов.'
            version: 1.0.0
    areas: # to filter documented areas
        default:
            path_patterns: [ '^/' ]
            host_patterns: [ ]
